#spring:
#  application:
#    name: mall-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#        - id: test
#          uri: https://baidu.com
#          predicates:
#            - Query=u,baidu
#
#server:
#  port: 9999